version: '2.4'
services:
  db:
    image: mysql
    container_name: mysqlBD
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - rodrigues_data:/var/lib/mysql

volumes:
  rodrigues_data: